title: GitHub Pages Website
description: This is just a website made with GitHub Pages and jekyll

remote_theme: just-the-docs/just-the-docs

color_scheme: light

footer_content: "Made with GitHub and Jekyll"

plugins:
  - jekyll-remote-theme